package async.apf.view.enums;

public enum ViewEventType {
    LOAD_INITIAL_CONFIG,
    LOAD_TARGET_CONFIG,
    SIMULATION_START,
    SIMULATION_RESTART,
    SIMULATION_CONTINUE,
    SIMULATION_PAUSE,
    SIMULATION_END,
    SET_SIMULATION_DELAY,
}
